### PR TITLE
Use Ansible's letsencrypt module.

### LINKED ISSUE #7: use a more common acme implementation
The current acme_tiny implementation (acme_lib.py) comes from a custom branch of an unmaintained fork.
For a long-term support perspective it'd be safer to choose a well-supported implementation since it's a hard-dependency for the whole role.

### PR DESCRIPTION
**Pull request by felixfontein**
fixes #7 

The Ansible `letsencrypt` module is documented [here](https://docs.ansible.com/ansible/latest/letsencrypt_module.html).

### CODE REVIEW

**Comment by felixfontein** [comment]
Next steps:
 * replace `acme_compact` with a smaller tool which just offers the required functionality (i.e. creating keys and CSRs);
 * find out how to get URLs of root and intermediate certificates from CA (looks like that's not really possible ATM; at least I couldn't find anything in [the specs](https://tools.ietf.org/html/draft-ietf-acme-acme-09));
 * more testing.

**Comment by felixfontein** [comment]
I've now added support for DNS challenges.

Also, there's a PR with ansible (ansible/ansible#34328) to add support for getting the intermediate certificate from the `letsencrypt` module.

Finally, there's (currently) an incompatible change in Ansible 2.5 (ansible/ansible#22074) which writes the intermediate certificate into the certificate file, if `fullchain` is not explicitly set to `false`. Since the module doesn't support this setting for 2.4, I can only add this setting here once 2.5 is released.

**Comment by felixfontein** [comment]
With the changes in b03d0846bcc573315b17b87ca718dd073989edc4 and with ansible/ansible#34541, I was able to successfully get wildcard certificates from the Let's Encrypt ACME v2 staging server! \o/

**Comment by felixfontein** [comment]
My current plan is to extend this to support both v1 and v2 endpoints, but I'm not sure whether I will manage this before the end of this week.

**Comment by apple4ever** [comment]
What's the ETA on this? I'd like to use DNS challenges. I use Dyn right now for my DNS, so I'll write an playbook for that and contribute. Or should I just try this branch and test it out for you?

**Comment by felixfontein** [comment]
My original plan was to integrate ACME v2 support as well, but I then still had the 'end of January 2018' deadline in my head. Since that's now delayed, there's no need to wait. I'll clean this up and merge this somewhen this weekend, so it should be ready by Monday.

**Comment by felixfontein** [comment]
Works fine with both the current `letsencrypt` module (devel version, but 2.4.x version should also work fine, except that Python 3 support there is flaky) and the ACME v2 support PR (ansible/ansible#34328). So this should be done.

**Comment by felixfontein** [comment]
(Rebase due to conflict.)

**Pull request merged**
